name: Docker Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t forecast-model-api .

      - name: Run tests
        run: |
          docker run --rm forecast-model-api /bin/sh -c "pytest"

      - name: Run Docker
        run: |
          docker run -p 8000:8000 forecast-model-api